const desc_table = {
  "1:1": "Button Click success",
  "1:2": "Button Click Failed",
  "2:1": "TextInput success",
  "2:2": "TextInput Failed",
  "3:1": "Navigation Success",
  "3:2": "Navigation Failed",
  "4:1": "Scroll Success",
  "4:2": "Scroll Failed",
  "6:1": "Keyboard Visible",
  "6:2": "Keyboard Hide",
  "7:1": "Back Button Press success",
  "7:2": "Back Button Press failed",
  "8:1": "App crashed due to js exception",
  "8:2": "App crashed due to native exception",
  "9:1": "Websocket connected",
  "9:2": "websocket closed",
  "9:3": "websoket error",
  "10:1": "App goes to background",
  "10:2": "App comes to foreground",
  "5:3": "Api response success",
  "5:2": "Api request Failed",
  "5:1": "Api request Success",
  "5:4": "Api response Failed",
  // NCS APP
  "1:1": "skip/next button clicked",
  "1:2": "In login screen username field focused",
  "1:3": "In login screen password field focused",
  "1:4": "In login screen password show/hide button clicked",
  "1:5": "In login screen Submit button clicked",
  "1:6": "In login screen Forgot Password clicked",
  "1:7": "In login screen Join With Meeting ID clicked",
  "1:8": "In Forgot Password screen Email address field focused",
  "1:9": "In Forgot Password screen Reset clicked",
  "1:10": "In Forgot Password screen Cancel clicked",
  "1:11": "In Forgot Password screen Ok is clicked after password reset action",
  "1:12": "In PBX tab Dialpad button clicked",
  "1:13": "In PBX tab Contacts button clicked",
  "1:14": "Global search icon clicked",
  "1:15": "In Global Search textInput focused",
  "1:16": "In Global Search People button clicked",
  "1:17": "In Global Search Group button clicked",
  "1:18": "In Global Search Messages button clicked",
  "1:19": "In Global Search Close icon clicked",
  "1:20": "In PBX tab All tab clicked",
  "1:21": "In PBX tab Incoming tab clicked",
  "1:22": "In PBX tab Outgoing tab clicked",
  "1:23": "In PBX tab Missed tab clicked",
  "1:24": "In PBX tab All tab Filter by date clicked",
  "1:25": "In PBX tab Incoming tab Filter by date clicked",
  "1:26": "In PBX tab Outgoing tab Filter by date clicked",
  "1:27": "In PBX tab Missed tab Filter by date clicked",
  "1:28": "In Filter By date modal start date selected",
  "1:29": "In Filter By date modal end date selected",
  "1:30": "In Filter By date modal Submit button clicked",
  "1:31": "In Bottom bar Chat tab clicked",
  "1:32": "Clicked on the chat user on Chat user list",
  "1:33": "Create Group button clicked",
  "1:34": "Create Button in Create group modal clicked",
  "1:35": "Cancel Button in Create group modal clicked",
  "1:36": "Close Icon in Create group modal clicked",
  "1:37": "In Bottom bar Meeting tab clicked",
  "1:38": "Start a meeting Button Clicked",
  "1:39": "Join a meeting Button Clicked",
  "1:40": "Join button clicked in Join a meeting screen",
  "1:41": "Cancel button clicked in Join a meeting screen",
  "1:42": "Audio enabled in Join a meeting screen",
  "1:43": "Audio disabled in Join a meeting screen",
  "1:44": "Video enabled in join a meeting screen",
  "1:45": "Video disabled in join a meeting screen",
  "1:46": "Leave/End meeting icon clicked in Meeting screen",
  "1:47": "Cancel button in End meeting Confirmation modal clicked",
  "1:48": "End for me button in End meeting Confirmation modal clicked",
  "1:49": "End for all button in End meeting Confirmation modal clicked",
  "1:50": "Unlock/Lock icon in Meeting screen clicked",
  "1:51": "Invite icon in Meeting screen clicked",
  "1:52": "Info icon in Meeting screen clicked",
  "1:53": "Raise hand in Meeting screen clicked",
  "1:54": "Mic icon in Meeting screen clicked",
  "1:55": "video icon in Meeting screen clicked",
  "1:56": "speaker icon in Meeting screen clicked",
  "1:57": "People icon in Meeting screen clicked",
  "1:58": "Chat icon in Meeting screen clicked"
};

module.exports = { desc_table };
